services:
  - type: web
    name: taskmaster
    env: node
    buildCommand: npm install --production=false && npm run build
    startCommand: npm start
    envVars:
      - key: MONGODB_URI
        value: mongodb+srv://bodasandeepsaiofficial:AKeM1S2CAVhdCHZp@task-manager.2vby3.mongodb.net/?retryWrites=true&w=majority&appName=task-manager
      - key: JWT_SECRET
        value: ee9616f1863c3fae8c1c280a7ad49847a0b058f8b68862020220b79aa970225d8909b9f55316f4f352ce0f1ad2096ecff9f2c3e4f825b44a39a596e65d612b2e
      - key: GEMINI_API_KEY
        value: AIzaSyDV41X9TmzQNV7_baYugpAw4qyoKNdK9Zw
      - key: NODE_ENV
        value: production 